name: Symfony

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ github.token }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: ctype, iconv

    - uses: actions/checkout@v2

    - name: Get Composer Cache Directory
      id: composer-cache-tools
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache Composer Directory
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache-tools.outputs.dir }}
        key: ${{ runner.os }}-composer-tools-${{ hashFiles('**/tools/php-cs-fixer/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-tools-

    - name: Validate composer config
      run: composer validate --strict

    - name: Install Dependencies
      run: composer install --working-dir=tools/php-cs-fixer -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Run PHPCSFixer
      run: composer cs-fix-ci