name: Symfony

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  symfony:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ github.token }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: ctype, iconv

    - uses: actions/checkout@v3

    - name: Install symfony-cli
      run: |
        curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh' | sudo -E bash
        sudo apt install symfony-cli

    - name: Copy .env.test.local
      run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Check requirements
      run: symfony check:requirements

    - name: Check security
      run: symfony check:security

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: |
        cp .env.ci .env.test
        cp .env.ci .env
        composer test